version: "2"
formatters:
  enable:
    - goimports
    - gofmt

run:
  tests: false

linters:
  settings:
    govet:
      enable:
        - shadow
    gocyclo:
      min-complexity: 30
    misspell:
      locale: US
  enable:
    - unused
    - errcheck
    - gocognit
    - gocyclo
    - govet
    - misspell
    - staticcheck
    - whitespace
